### ISSUE TITLE
Seminar fee pricing and taxes

### ISSUE THREAD

**Issue by jasloe** [jasloe/awa#15]
Deep in the weeds on commerce since early this morning.

Seminar pricing generally follows this pattern:

### Entire seminar (AWA)
One day only (non-AWA, e.g. Friday only, Saturday only, Sunday only)

### Entire seminar (non-AWA)
One day only (non-AWA, e.g. Friday only, Saturday only, Sunday only)

#### Four day seminars add the following variant:
Thurs. or Sun. only
Fri. or Sat. only

Fees are assessed at a fixed price for each variant. There are no explicit sales taxes or VAT assessed at time of checkout, whether in the US, EU, Middle East, etc.

We can configure product types and variants listed above then pass the seminar fee to the payment processor *without* assessing sales tax. Can you confirm with HQ that this is the general payment pattern and that taxes are never collected?

**Comment by 21centuryaikido** [comment]
Yes, on it.

**Comment by jasloe** [comment]
@21centuryaikido -- Another question: Are credit card payments abroad charged exclusively in US dollars?

**Comment by 21centuryaikido** [comment]
On it

**Comment by jasloe** [comment]
@21centuryaikido -- There are 131 supported payment gateways listed here:

https://docs.drupalcommerce.org/commerce2/developer-guide/payments/available-gateways

This project should support only the following:

Square
PayPal
Authorize.net

Square supports AUD, CAD, GBP, JPY, USD in AU, CA, JP, UK, US.
PayPal is supported mostly everywhere....unfortunately Lebanese currency is not supported (sorry, Klinger).

I suppose we'll need to set all of these up for HQ. For testing purposes, there are built-in demos but we should do a live test with AOSB Square and PP accounts.

**Comment by jasloe** [comment]
Lastly, Authorize.net charges 2.9% plus $0.30 per transaction. As far as I know, this is the standard rate. Does HQ get better rates through their processor?

p.s. Authorize.net is basically a subsidiary of Visa.

**Comment by 21centuryaikido** [comment]
Converge charges us 1.99%. Not sure the per transaction fee. About the same, I think. I don't the systems capabilities beyond what I do with it. You can check it out at support.convergepay.com.

**Comment by jasloe** [comment]
Going with Authorize.net using Accept.js for now. Re-open if anything changes.
