### ISSUE TITLE
Migrating AWA member to profiles

### ISSUE THREAD

**Issue by jasloe** [jasloe/awa#23]

**Comment by jasloe** [comment]
Dependencies: 

- [ ] #24

**Comment by jasloe** [comment]
#25 needs geolocation cleanup. Low priority.

@21centuryaikido: Looking at the spreadsheets. Just to clarify, the canonical column headers I put together (row B, Alaska) needs to match across all documents.

Alaska has 36 columns A-AJ. Mountain Spirit as A-AL. Razgrad has A-AB. To further clarify, for example, Razgrad does not have the address columns. Even if they're empty/unpopulated they still need to be there so that each spreadsheet can be merged into a single document and imported into the database.

See the attached document for a report on each spreadsheet's disposition.
[out.txt](https://github.com/jasloe/awa/files/4209377/out.txt)

This needs to be fixed before migrating.

**Comment by jasloe** [comment]
Looking over the files again, there may be a way to fix this programmatically.

**Comment by jasloe** [comment]
Oof...well I tapped into another project and wrote something in Catmandu to parse the files. It's a metalanguage so pretty easy to read. I'm converting everything to JSON format, running the code below, then running ```head -1 somef-file-name.csv``` to confirm that each filename has the correct header.

```
retain(member_number,dojo_id,book_issued,given_name,family_name,address_street,address_city,address_state,telephone,email,dob,active,youth,date_kyu_2,date_kyu_1,aikikai_number,iaf_number,date_shodan,date_nidan,date_sandan,date_yondan,date_godan)

replace_all("active","X","1")
replace_all("book_issued","X","1")
replace_all("youth","X","1")

unless exists('address_country')
  add_field('address_country')
end

unless exists('address_street')
  add_field('address_street')
end

move_field('address_street','address_street1')

add_field('address_street2')

unless exists('address_city')
  add_field('address_city')
end

unless exists('address_state')
  add_field('address_state')
end

unless exists('address_zip')
  add_field('address_zip')
end

move_field('address_street','address_street1')

add_field('address_street2')
```

I'm returning the header from JSON in alphabetical order then running ```cat``` to join them into a single file for import into Drupal. Kind of mess but it works.

**Comment by jasloe** [comment]
The only fields we're keeping are in this ```retain``` statement above, i.e. I ditched everything before 2nd kyu.

**Comment by 21centuryaikido** [comment]
The migration worked? I'm working on the kiku matsu file. It's actually the worst of them. Should I do anything differently?

**Comment by jasloe** [comment]
Still working on cleaning up the spreadsheets. I'll take care of KM.

**Comment by jasloe** [comment]
This is done.
