### ISSUE TITLE
Get AWA logo file from Kiku Matsu

### ISSUE THREAD

**Issue by jasloe** [jasloe/awa#3]
The logo on the current site is a little soft. Would be great to have a larger file, suitable for both print and web.

**Comment by 21centuryaikido** [comment]
![C9BFA014-657A-4E31-8E36-623F6AFAFEE7](https://user-images.githubusercontent.com/60327710/73141905-af3f2800-404e-11ea-92d8-1cb092282227.png)

**Comment by 21centuryaikido** [comment]
Uploaded. Get it?

**Comment by jasloe** [comment]
Yep.
