### ISSUE TITLE
Staging site access

### ISSUE THREAD

**Issue by jasloe** [jasloe/awa#9]
@21centuryaikido –– server infrastructure and backend code, web server, and database are live. 

Nothing to see here quite yet but I'll grant you administrator access once I get the basics ironed out. Just let me know you can reach the site for now.

**Comment by 21centuryaikido** [comment]
How do I reach it? Is there an URL?

**Comment by jasloe** [comment]
Oops...

http://awa.minorscience.com

**Comment by 21centuryaikido** [comment]
Is this what I should see? Links don't lead any where.

**Comment by jasloe** [comment]
You should see this:

<img width="560" alt="Screen Shot 2020-01-27 at 4 00 47 PM" src="https://user-images.githubusercontent.com/1063667/73213478-458e4f00-411e-11ea-9aa2-fbf202272d47.png">
